language: java

jdk:
  - openjdk11

install: mvn -f gson install -DskipTests=true
script: mvn -f gson test

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
